get correct go version

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,6 +21,13 @@ jobs:
       with:
         go-version: 1.20
 
+    - name: Ensure correct Go version
+      run: |
+        go version
+        if [[ $(go version) != *"go1.20"* ]]; then
+          echo "Error: Incorrect Go version. Expected Go 1.20." && exit 1
+        fi
+
     - name: Install dependencies
       run: go mod tidy
 
